import type { Metadata } from "next";
import { Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";
import { Backdrop } from "@/components/Backdrop";

export const bebas = Bebas_Neue({
  weight: ["400"],
  style: "normal",
  subsets: ["latin-ext"],
});
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(bebas.className, poppins.className)}>
        <Header />
        <Backdrop />
        {children}
      </body>
    </html>
  );
}
